# Generated by Django 3.2.4 on 2021-06-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_es'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='es',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='ianalysis',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='sanalysis',
            options={'ordering': ('-date',)},
        ),
    ]
